version: '3.4'

services:

  api:
    container_name: feedfin-api
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      - FEEDFIN_DEBUG=true
      - DATABASE_URL=postgres://postgres:postgres@db:5432/feedfin_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/feedfin_test
    depends_on:
      - db
    links:
      - db

  db:
    container_name: feedfin-db
    build: ./database
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['pg_isready']
